
services:
  api:
    build: .
    image: sistema-financeiro:dev
    container_name: sistema-financeiro-api
    env_file:
      - .env
    networks:
      - sistema-financeiro-net
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    restart: always
    user: "node"
    depends_on:
      db:
        condition: service_healthy
    environment:
       DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASS}@db:${DB_PORT}/${DATABASE_NAME}
       PORT: ${PORT}
       TOKEN_SECRET: ${TOKEN_SECRET}
       NODE_ENV: ${NODE_ENV}

    volumes:
      - uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:${INTERNAL_PORT}/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    container_name: sistema-financeiro-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    networks:
      - sistema-financeiro-net
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  sistema-financeiro-net:
    driver: bridge

volumes:
  uploads:
