services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-financeiro-api
    networks:
      - sistemafinanceironet
    ports:
      - "${API_PORT_INTERNAL}:${API_PORT_EXTERNAL}" 
    restart: always
    user: "node"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:${API_PORT_EXTERNAL/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: ["yarn", "dev"] 

  db:
    image: postgres:16
    container_name: sistemafinanceiro-db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-trust}
    networks:
      - sistemafinanceironet
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
       - "${Database_PORT}:${Database_PORT}" 
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  sistemafinanceironet:
    driver: bridge
